baseURL = "https://collantes.us/"
languageCode = "en-us"
title = "David"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableEmoji = true
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) License"
rssLimit = 20
disableKinds = ['taxonomyTerm', 'section']

[params]
  # Open Graph details for embedding.
  description = "David Collantes' personal website, and blog."
  images = ["/resources/opengraph_card.png"]
  title = "David Collantes"
  interim = "david#"

[taxonomies]
  series = "series"

[permalinks]
  "/" = "/:year/:month/:day/:slug/"

[author]
  name = "David Collantes"
  email = "david@collantes.us"

[markup.goldmark.renderer]
  # Allow HTML inclides. Since Hugo 0.60.0 this is now required (another undocumented breaking change).
  unsafe= true
